import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Providers> */}
        <div className="relative flex min-h-dvh flex-col bg-background">
          {/* <Header /> */}
          <main className="flex-1">{children} </main>
          <Footer />
        </div>
        {/* </Providers> */}
      </body>
    </html>
  );
}
